org: alleroif
app: test
service: microservice-transaction
frameworkVersion: '3'
plugins:
  - serverless-auto-swagger

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:488791404709:table/TransactionTable

functions:
  createTransaction:
    handler: src/services/createTransaction.createTransaction
    events:
      - httpApi:
          path: /transaction
          method: post
  getTransaction:
    handler: src/services/getTransaction.getTransaction
    events:
      - httpApi:
          path: /transaction
          method: get
  getTransactionById:
    handler: src/services/getTransactionById.getTransactionById
    events:
      - httpApi:
          path: /transaction/{id}
          method: get

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TransactionTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
